### ISSUE TITLE
Btn.awaitOneClick on wrong context

### ISSUE THREAD

**Issue by chillbrodev** [Beepiz/BleScanCoroutines#7]
In the mobile sample when a user taps on the start scan button the app crashes with the following stack track because the action is not called on the Main Thread.

`19232-19252/com.beepiz.blescancoroutines.sample E/MainActivity: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7760)
        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3780)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
        at android.view.View.setFlags(View.java:14096)
        at android.view.View.setEnabled(View.java:10016)
        at android.widget.TextView.setEnabled(TextView.java:2096)
        at com.beepiz.blescancoroutines.sample.common.extensions.SuspendViewsKt.awaitOneClick(SuspendViews.kt:15)
        at com.beepiz.blescancoroutines.sample.common.extensions.SuspendViewsKt.awaitOneClick$default(SuspendViews.kt:13)
        at com.beepiz.blescancoroutines.sample.MainActivity.consumeScanStartStops(MainActivity.kt:74)
        at com.beepiz.blescancoroutines.sample.MainActivity$consumeScanStartStops$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

**Comment by LouisCAD** [comment]
Hi, I'm not sure how this can even happen as the `consumeScanStartStops` function is [only ever called from `onCreate`](https://github.com/Beepiz/BleScanCoroutines/blob/5904bc44089e722145f987d653f1c77f479b9af2/sample-app-mobile/src/main/java/com/beepiz/blescancoroutines/sample/MainActivity.kt#L47) which should be called on the main thread only.

Did you edit anything?

**Comment by chillbrodev** [comment]
Nope, I just pulled the repo and ran it. I can try again later on with a fresh pull and give you some more details. Great library btw really shows the power of channels.
